version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.3
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            pip install coverage codecov
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: Generate config.yml
          command: |
            sed -e "s|__ENV_TYPE__|circleci|g" config/config.tmpl.yml > config/config.yml.tmp1
            sed -e "s|__COINONE_ACCESS_TOKEN__|$COINONE_ACCESS_TOKEN|g" config/config.yml.tmp1 > config/config.yml.tmp2
            sed -e "s|__COINONE_SECRET_KEY__|$COINONE_SECRET_KEY|g" config/config.yml.tmp2 > config/config.yml
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            pytest --cov=./ -sv
            codecov
      - store_artifacts:
          path: test-reports
          destination: test-reports
